test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.subdir"]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------
